// STUB — will be replaced by task-06 on merge
// task-07-frontend-inbox-picker created this stub to unblock parallel implementation.
// Do NOT edit this file — task-06 owns the canonical definition.
export interface IInbox {
  _id: string
  name: string
  kind: 'messenger' | 'chat'
  inboxToken: string
  webhookUrl: string | null
  active: boolean
}
