web: tsx server.ts
scaler: tsx scaler.ts
worker: tsx worker.ts
worker2: tsx worker.ts
worker3: tsx worker.ts
worker4: tsx worker.ts
worker5: tsx worker.ts
worker6: tsx worker.ts
worker7: tsx worker.ts
worker8: tsx worker.ts
worker9: tsx worker.ts
worker10: tsx worker.ts
worker11: tsx worker.ts
worker12: tsx worker.ts
worker13: tsx worker.ts
worker14: tsx worker.ts
worker15: tsx worker.ts
