web: node server.js
scaler: node scaler.js
worker: node worker.js
worker2: node worker.js
worker3: node worker.js
worker4: node worker.js
worker5: node worker.js
worker6: node worker.js
worker7: node worker.js
worker8: node worker.js
worker9: node worker.js
worker10: node worker.js
worker11: node worker.js
worker12: node worker.js
worker13: node worker.js
worker14: node worker.js
worker15: node worker.js
