// STUB — will be replaced by task-06 on merge
// task-07-frontend-inbox-picker created this stub to unblock parallel implementation.
// Do NOT edit this file — task-06 owns the canonical implementation.
import type { IInbox } from '../types/inbox'

export const getInboxes = async (_params: object): Promise<IInbox[]> => []
